name: Updates

on:
  schedule:
    - cron: "0 12 * * *"
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6

      - name: Update gemfile and install dependencies
        run: chmod +x ./updateGemfile.sh && ./updateGemfile.sh

      - name: Run test
        run: bundle exec ruby simple_test_script.rb
        env:
          APPLITOOLS_API_KEY: ${{ secrets.APPLITOOLS_API_KEY }}

      - uses: mikeal/publish-to-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: 'master'